title: Anubis Documentation
description: Guideline for Using Anubis Mobile Manipulator
theme: just-the-docs

url: https://chomeed.github.io/anubis

aux_links:
  Template Repository: https://chomeed.github.io/anubis
